<?php

/**
 * One-time web installer for shared hosting without SSH / CLI access
 * (InfinityFree, Byet.host, ...).
 *
 * 1. Upload the whole Laravel app into htdocs/ (see build script).
 * 2. Create the MySQL database in the hosting control panel.
 * 3. Fill in the credentials in htdocs/.env.
 * 4. Open:  https://<your-site>/setup.php?token=<APP_SETUP_TOKEN>
 *    (APP_SETUP_TOKEN is generated by the build script into .env)
 * 5. Migrations and seeders run automatically.
 * 6. DELETE this file from the File Manager when done.
 */

declare(strict_types=1);
use Illuminate\Contracts\Console\Kernel;
use Illuminate\Support\Facades\Artisan;

// Works whether this file sits in htdocs/ or htdocs/public/.
$base = str_ends_with(__DIR__, DIRECTORY_SEPARATOR.'public') ? dirname(__DIR__) : __DIR__;

require $base.'/vendor/autoload.php';

// Load .env before checking the token.
$dotenv = Dotenv\Dotenv::createUnsafeImmutable($base);
$dotenv->safeLoad();

$expected = (string) (getenv('APP_SETUP_TOKEN') ?: '');
$token = (string) ($_GET['token'] ?? '');

if ($expected === '' || ! hash_equals($expected, $token)) {
    http_response_code(403);
    exit('Forbidden: missing or wrong setup token.');
}

header('Content-Type: text/plain; charset=utf-8');

try {
    $app = require $base.'/bootstrap/app.php';
    $kernel = $app->make(Kernel::class);
    $kernel->bootstrap();

    Artisan::call('optimize:clear');
    echo "optimize:clear ... OK\n";

    Artisan::call('migrate', ['--force' => true]);
    echo "migrate .......... OK\n";

    Artisan::call('db:seed', ['--force' => true]);
    echo "db:seed .......... OK\n";

    try {
        Artisan::call('storage:link');
        echo "storage:link ..... OK\n";
    } catch (Throwable $e) {
        echo "storage:link ..... skipped (symlinks may be disabled on this host)\n";
    }

    echo "\nSetup finished. Login: admin@itams.local / password\n";
    echo "IMPORTANT: delete setup.php now.\n";
} catch (Throwable $e) {
    http_response_code(500);
    echo "Setup FAILED:\n".$e->getMessage()."\n";
}
